pipeline {
    
    agent any
    
    tools {
        nodejs "node"
    }
    
    environment {
        IMAGE_NAME = "jeevanugale/nodejs-app"
        TAG = "${BUILD_NUMBER}"
    }
    
    stages {

        stage ('AWS configure') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh '''
                    aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                    aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                    aws configure set default.region ap-south-1
                    '''
                }
            }
        }
        stage ('Generate SSH Key for EC2') {
            steps {
                sh '''
                cd Iac
                ssh-keygen -t rsa -b 4096 -f jenkins_key -N ""
                '''
            }
        }

        stage ('Terraform Init and Validate') {
            steps {
                sh '''
                cd Iac
                terraform init
                terraform validate
                '''
            }
        }

        stage ('Terraform Plan') {
            steps {
                sh '''
                cd Iac
                terraform plan -out=tfplan
                '''
            }
        }

        stage ('Terraform Apply') {
            steps {
                sh '''
                cd Iac
                terraform apply -auto-approve tfplan
                '''
            }
        }

        stage ('Run Test') {
            steps {
                sh '''
                cd app
                npm install
                npm test
                '''
            }
        }

        stage ('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG -f docker/Dockerfile .'
            }
        }

        stage ('Trivy Image Security Scan') {
            steps {
                sh 'trivy image $IMAGE_NAME:$TAG'
            }
        }

        stage ('Push Image') {
            steps {
                script {
            withDockerRegistry(
                credentialsId: 'docker-login',
                url: 'https://index.docker.io/v1/'
            ) {
                sh '''
                docker push $IMAGE_NAME:$TAG
                '''
              }
                }
            }
        }
    }
}