pipeline {
    
    agent any
    
    tools {
        nodejs "node"
    }
    
    environment {
        IMAGE_NAME = "jeevanugale/nodejs-app"
        TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage ('Run Test') {
            steps {
                sh '''
                cd app
                npm install
                npm test
                '''
            }
        }
        stage ('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG -f docker/Dockerfile .'
            }
        }
        stage ('Trivy Image Security Scan') {
            steps {
                sh 'trivy image $IMAGE_NAME:$TAG'
            }
        }
        stage ('Push Image') {
            steps {
                script {
            withDockerRegistry(
                credentialsId: 'docker-login',
                url: 'https://index.docker.io/v1/'
            ) {
                sh '''
                docker push $IMAGE_NAME:$TAG
                '''
            }
        }
            }
        }
    }
}